menu.general.locked=&c✗ Not Unlocked
menu.general.unlocked=&a✓ Unlocked!

menu.general.selected.false=&e✦ Click to Select
menu.general.selected.true=&a✓ Selected

menu.main.title=&8Parkour Menu

menu.main.greenhouse.title=&2&lGreenhouse
menu.main.greenhouse.desc.0=&7Join the Greenhouse!

menu.main.courses.title=&c&lCourses
menu.main.courses.desc.0=&7View a list of courses!

menu.main.progjumps.title=&a&lProgJumps
menu.main.progjumps.desc.0=&7Rankup-style system from Ibis Network!

menu.main.cosmetics.title=&f&lCosmetics
menu.main.cosmetics.desc.0=&7Change your tag, chat color, hotbar, and more!

menu.main.onejump.title=&6&lOneJump
menu.main.onejump.desc.0=&7Courses with 1 Jump per Checkpoint!

menu.main.creative.title=&e&lCreative
menu.main.creative.desc.0=&7Join the plot world!

menu.main.spawn.title=&b&lSpawn
menu.main.spawn.desc.0=&7Go back to spawn!

menu.main.radio.title=&c&lRadio
menu.main.radio.desc.0=&7Play any of the Scoville songs!

menu.main.achievements.title=&a&lAchievements
menu.main.achievements.desc.0=&7View your achievements!

menu.main.levels.title=&a&lLevel Rewards
menu.main.levels.desc.0=&7View the leveling rewards!

menu.main.admin.title=&c&lAdmin Panel
menu.main.admin.desc.0=&7Edit aspects of the server!

menu.admin.title=&8Admin Panel

menu.admin.courses.title=&c&lCourses
menu.admin.courses.desc.0=&7Edit courses!

menu.admin.players.title=&e&lPlayers
menu.admin.players.desc.0=&7Edit player data!

menu.admin.seasons.title=&a&lSeasons
menu.admin.seasons.desc.0=&7Edit season data!

menu.generic.prev.title=&bBack
menu.generic.next.title=&bNext
menu.generic.selected.desc.0=&a&lSelected
menu.generic.selected.desc.1=&8&lNot Selected
menu.generic.confirm.title=&a&lConfirm
menu.generic.confirm.desc.0=&7Confirm these changes?

menu.courses.type.title=&8Course Type
menu.courses.type.user.title=&a&lUser
menu.courses.type.rankup.title=&f&lRankup
menu.courses.type.oj.title=&e&lOneJump

menu.courses.title=&8Course List

menu.courses.course.diff.0=&5Unknown - 0/10
menu.courses.course.diff.1=&2Sweet - 1/10
menu.courses.course.diff.2=&aTangy - 2/10
menu.courses.course.diff.3=&aSavory - 3/10
menu.courses.course.diff.4=&eZesty - 4/10
menu.courses.course.diff.5=&eSpicy - 5/10
menu.courses.course.diff.6=&6Hot - 6/10
menu.courses.course.diff.7=&6Sizzling - 7/10
menu.courses.course.diff.8=&cFiery - 8/10
menu.courses.course.diff.9=&cScorching - 9/10
menu.courses.course.diff.10=&4Blazing - 10/10

menu.courses.course.diff.oj={1} Jumps - Difficulty 3

menu.courses.course.cr=&7Clear Rate
menu.courses.course.ur=User Rating
menu.courses.course.tc=Times Completed

menu.admin.courses.new=&2&lNew Course

menu.admin.courses.create.prompt=&8[&eScoville&8] &7Please input the course name:
menu.admin.courses.create.title=&8Create: {0}

menu.admin.courses.create.colorname.title=&f&lColored Name
menu.admin.courses.create.colorname.desc.0=&7Click here to set the
menu.admin.courses.create.colorname.desc.1=&7colored name for the
menu.admin.courses.create.colorname.desc.2=&7course in the GUI!
menu.admin.courses.create.colorname.desc.3=&7Currently: {0}
menu.admin.courses.create.colorname.prompt=&8[&eScoville&8] &7Please input the course name &ewith colors&7:

menu.admin.courses.create.guiitem.title=&f&lGUI Item
menu.admin.courses.create.guiitem.desc.0=&7Place an item here to
menu.admin.courses.create.guiitem.desc.1=&7set the item to be
menu.admin.courses.create.guiitem.desc.2=&7used in the GUI!

menu.admin.courses.create.authors.title=&f&lAuthors
menu.admin.courses.create.authors.desc.0=&7Click here to select
menu.admin.courses.create.authors.desc.1=&7the course authors!
menu.admin.courses.create.authors.desc.3=&7Currently: {0}

menu.admin.courses.create.diff.title=&{0}&lDifficulty: {1}
menu.admin.courses.create.rank.title=&{0}&lRank: {1}

menu.admin.courses.create.hallway.title=&e&lHallways
menu.admin.courses.create.rankup.title=&f&lRankup
menu.admin.courses.create.open.title=&a&lOpen

menu.admin.courses.create.confirm.title=&a&lConfirm
menu.admin.courses.create.confirm.desc.0=&7Confirm these configurations

menu.admin.courses.create.created=&8[&a*&8] {0} &7successfully &acreated&7!

menu.admin.courses.create.title.rankup=&8Create Rankup
menu.admin.courses.create.rankup.exists=&8[&c*&8] &7All &crankups &7are already created!

menu.admin.courses.create.oj.jumps.title=&f&l&o{0} Jumps

menu.confirm.title=&8&lAre you sure?
menu.confirm.yes.title=&a&lYes
menu.confirm.no.title=&c&lNo

menu.achievements.type.title=&8Achievements
menu.achievements.type.easy.title=Easy Achievements
menu.achievements.type.medium.title=Medium Achievements
menu.achievements.type.hard.title=Hard Achievements
menu.achievements.type.tiered.title=Tiered Achievements
menu.achievements.type.special.title=Special Achievements

menu.achievements.list.unlock_rate=&7Unlock Rate

menu.cosmetics.title=&8Cosmetics

menu.cosmetics.tags.title=&f&lTags
menu.cosmetics.chat_colors.title=&7&lChat Colors
menu.cosmetics.hotbars.title=&6&lHotbars
menu.cosmetics.particles.title=&9&lParticles
menu.cosmetics.disguises.title=&a&lDisguises
menu.cosmetics.hats.title=&e&lHats
menu.cosmetics.join_messages.title=&2&lJoin Messages
menu.cosmetics.win_messages.title=&e&lWin Messages

menu.cosmetics.chat_color.inv.title=&8Chat Colors

menu.cosmetics.chat_color.dark_green.title=&2&lDark Green Chat
menu.cosmetics.chat_color.dark_green.desc=&7Unlocked at &2&lPepperoncini&7!
menu.cosmetics.chat_color.green.title=&a&lLight Green Chat
menu.cosmetics.chat_color.green.desc=&7Unlocked at &2&lPoblano&7!
menu.cosmetics.chat_color.yellow.title=&e&lYellow Chat
menu.cosmetics.chat_color.yellow.desc=&7Unlocked at &e&lSerrano&7!
menu.cosmetics.chat_color.gold.title=&6&lOrange Chat
menu.cosmetics.chat_color.gold.desc=&7Unlocked at &6&lThai&7!
menu.cosmetics.chat_color.red.title=&c&lLight Red Chat
menu.cosmetics.chat_color.red.desc=&7Unlocked at &c&lGhost&7!
menu.cosmetics.chat_color.dark_red.title=&4&lDark Red Chat
menu.cosmetics.chat_color.dark_red.desc=&7Unlocked at &4&lCarolina Reaper&7!
menu.cosmetics.chat_color.dark_gray.title=&8&lDark Gray Chat
menu.cosmetics.chat_color.dark_gray.desc=&7Unlocked at &8&lCapsaicin&7!
menu.cosmetics.chat_color.light_purple.title=&d&lPink Chat
menu.cosmetics.chat_color.light_purple.desc=&7Unlocked at &a&lLevel 40&7!
menu.cosmetics.chat_color.dark_purple.title=&5&lDark Purple Chat
menu.cosmetics.chat_color.dark_purple.desc=&7Unlocked at &a&lLevel 80&7!
menu.cosmetics.chat_color.white.title=&f&lWhite Chat
menu.cosmetics.chat_color.white.desc=&7Default chat color!

menu.cosmetics.join_message.inv.title=&8Join & Leave Messages

menu.cosmetics.join_message.mr_cool.title=&e&lMr. Cool Login Messages
menu.cosmetics.join_message.mr_cool.desc=&7Unlocked at &a&lLevel 14&7!
menu.cosmetics.join_message.shakespeare.title=&7&lShafkespearean Login Messages
menu.cosmetics.join_message.shakespeare.desc=&7Unlocked at &a&lLevel 34&7!
menu.cosmetics.join_message.superhero.title=&9&lSuperhero Login Messages
menu.cosmetics.join_message.superhero.desc=&7Unlocked at &a&lLevel 54&7!
menu.cosmetics.join_message.aviation.title=&8&lAviation Login Messages
menu.cosmetics.join_message.aviation.desc=&7Unlocked at &a&lLevel 74&7!
menu.cosmetics.join_message.monarch.title=&6&lMonarch Login Messages
menu.cosmetics.join_message.monarch.desc=&7Unlocked at &a&lLevel 94&7!
menu.cosmetics.join_message.reversed.title=&a&lReversed Login Messages
menu.cosmetics.join_message.reversed.desc=&7Unlocked with the &e&lMoron Rank&7!
menu.cosmetics.join_message.stinky.title=&6&lSmelly Login Messages
menu.cosmetics.join_message.stinky.desc=&7Unlocked with the &c&lBuffoon Rank&7!
menu.cosmetics.join_message.reset.title=&cReset Join Message