menu.main.title=&8Parkour Menu

menu.main.greenhouse.title=&2&lGreenhouse
menu.main.greenhouse.desc.0=&7Join the Greenhouse!

menu.main.courses.title=&c&lCourses
menu.main.courses.desc.0=&7View a list of courses!

menu.main.progjumps.title=&a&lProgJumps
menu.main.progjumps.desc.0=&7Rankup-style system from Ibis Network!

menu.main.cosmetics.title=&f&lCosmetics
menu.main.cosmetics.desc.0=&7Change your tag, chat color, hotbar, and more!

menu.main.onejump.title=&6&lOneJump
menu.main.onejump.desc.0=&7Courses with 1 Jump per Checkpoint!

menu.main.creative.title=&e&lCreative
menu.main.creative.desc.0=&7Join the plot world!

menu.main.spawn.title=&b&lSpawn
menu.main.spawn.desc.0=&7Go back to spawn!

menu.main.radio.title=&c&lRadio
menu.main.radio.desc.0=&7Play any of the Scoville songs!

menu.main.achievements.title=&a&lAchievements
menu.main.achievements.desc.0=&7View your achievements!

menu.main.levels.title=&a&lLevel Rewards
menu.main.levels.desc.0=&7View the leveling rewards!

menu.main.admin.title=&c&lAdmin Panel
menu.main.admin.desc.0=&7Edit aspects of the server!

menu.admin.title=&8Admin Panel

menu.admin.courses.title=&c&lCourses
menu.admin.courses.desc.0=&7Edit courses!

menu.admin.players.title=&e&lPlayers
menu.admin.players.desc.0=&7Edit player data!

menu.admin.seasons.title=&a&lSeasons
menu.admin.seasons.desc.0=&7Edit season data!

menu.generic.prev.title=&bBack
menu.generic.next.title=&bNext
menu.generic.selected.desc.0=&a&lSelected
menu.generic.selected.desc.1=&8&lNot Selected
menu.generic.confirm.title=&a&lConfirm
menu.generic.confirm.desc.0=&7Confirm these changes?

menu.courses.type.title=&8Course Type
menu.courses.type.user.title=&a&lUser
menu.courses.type.rankup.title=&f&lRankup
menu.courses.type.oj.title=&e&lOneJump

menu.courses.title=&8Course List

menu.courses.course.diff.0=&5Unknown - 0/10
menu.courses.course.diff.1=&2Sweet - 1/10
menu.courses.course.diff.2=&aTangy - 2/10
menu.courses.course.diff.3=&aSavory - 3/10
menu.courses.course.diff.4=&eZesty - 4/10
menu.courses.course.diff.5=&eSpicy - 5/10
menu.courses.course.diff.6=&6Hot - 6/10
menu.courses.course.diff.7=&6Sizzling - 7/10
menu.courses.course.diff.8=&cFiery - 8/10
menu.courses.course.diff.9=&cScorching - 9/10
menu.courses.course.diff.10=&4Blazing - 10/10

menu.courses.course.diff.oj={1} Jumps - Difficulty 3

menu.courses.course.cr=&7Clear Rate
menu.courses.course.ur=User Rating
menu.courses.course.tc=Times Completed

menu.admin.courses.new=&2&lNew Course

menu.admin.courses.create.prompt=&8[&eScoville&8] &7Please input the course name:
menu.admin.courses.create.title=&8Create: {0}

menu.admin.courses.create.colorname.title=&f&lColored Name
menu.admin.courses.create.colorname.desc.0=&7Click here to set the
menu.admin.courses.create.colorname.desc.1=&7colored name for the
menu.admin.courses.create.colorname.desc.2=&7course in the GUI!
menu.admin.courses.create.colorname.desc.3=&7Currently: {0}
menu.admin.courses.create.colorname.prompt=&8[&eScoville&8] &7Please input the course name &ewith colors&7:

menu.admin.courses.create.guiitem.title=&f&lGUI Item
menu.admin.courses.create.guiitem.desc.0=&7Place an item here to
menu.admin.courses.create.guiitem.desc.1=&7set the item to be
menu.admin.courses.create.guiitem.desc.2=&7used in the GUI!

menu.admin.courses.create.authors.title=&f&lAuthors
menu.admin.courses.create.authors.desc.0=&7Click here to select
menu.admin.courses.create.authors.desc.1=&7the course authors!
menu.admin.courses.create.authors.desc.3=&7Currently: {0}

menu.admin.courses.create.diff.title=&{0}&lDifficulty: {1}
menu.admin.courses.create.rank.title=&{0}&lRank: {1}

menu.admin.courses.create.hallway.title=&e&lHallways
menu.admin.courses.create.rankup.title=&f&lRankup
menu.admin.courses.create.open.title=&a&lOpen

menu.admin.courses.create.confirm.title=&a&lConfirm
menu.admin.courses.create.confirm.desc.0=&7Confirm these configurations

menu.admin.courses.create.created=&8[&a*&8] {0} &7successfully &acreated&7!

menu.admin.courses.create.title.rankup=&8Create Rankup
menu.admin.courses.create.rankup.exists=&8[&c*&8] &7All &crankups &7are already created!

menu.admin.courses.create.oj.jumps.title=&f&l&o{0} Jumps

menu.confirm.title=&8&lAre you sure?
menu.confirm.yes.title=&a&lYes
menu.confirm.no.title=&c&lNo

menu.achievements.type.title=&8Achievements
menu.achievements.type.easy.title=Easy Achievements
menu.achievements.type.medium.title=Medium Achievements
menu.achievements.type.hard.title=Hard Achievements
menu.achievements.type.tiered.title=Tiered Achievements
menu.achievements.type.special.title=Special Achievements

menu.achievements.list.unlocked=&a✓ Unlocked!
menu.achievements.list.locked=&c✗ Not Unlocked
menu.achievements.list.unlock_rate=&7Unlock Rate